//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ESEIM.Models
{
    [Table("PIN_DATA")]
    public class PinData
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string PinDataType { get; set; }
		public int PinId { get; set; }
        public string UserId { get; set; }
		public string CreatedBy { get; set; }
        public DateTime CreatedTime { get; set; }
		public string UpdatedBy { get; set; }
        public DateTime UpdatedTime { get; set; }
		public string DeletedBy { get; set; }
        public DateTime DeletedTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}